In [56]:
import sys
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('expand_frame_repr', False)
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os
import datetime as dt
import sklearn
import re

In [57]:
if os.getcwd()[9:14] == 'ssoma':
    file_path = "C:\\Users\\ssoma\\OneDrive - Bayer\\Personal Data-R90PQ30R\\Analytics\\house-pricing\\input-data\\st-peters\\"
else:
    file_path = "C:\\Users\\sivac\\Documents\\Analytics\\house-pricing\\input-data\\st-peters\\"


file_list = os.listdir(file_path)
for i in file_list:
    i = file_path + i
    file = pd.read_csv(i)
    
    if 'df' in globals():
        df = pd.concat([df, file])
    else:
        df = file

print(f'Raw dataset shape: {df.shape}')

df_new = df[['MAILING_ADDR', 'MAILING_ZIP', 'SUBDIVISION', 'SCHOOL_DISTRICT', 'LOT_SIZE', 'YEAR_BUILT', 'QUALITY_CODE', 'BEDROOMS', 'BATHROOMS',
            'HALF_BATHROOMS', 'TOTAL_ROOMS', 'ARCHITECTURAL_STYLE', 'TOTAL_AREA', 'BASE_AREA', 'BASEMENT_AREA','BASEMENT_FINISHED_AREA',
            'PARKING_AREA', 'LAND_VALUE', 'LAST_SALE_PRICE', 'LAST_SALE_DATE', 'MARKET_VALUE', 'LAST_SALE_UPSF']]

df_new = df_new.drop_duplicates().reset_index(drop=True)
print(f'Raw dataset shape with duplicates removed: {df_new.shape}')
df_new.head()

Raw dataset shape: (3487, 34)
Raw dataset shape with duplicates removed: (3275, 22)

        MAILING_ADDR MAILING_ZIP    SUBDIVISION SCHOOL_DISTRICT   LOT_SIZE  YEAR_BUILT              QUALITY_CODE  BEDROOMS  BATHROOMS  HALF_BATHROOMS  TOTAL_ROOMS      ARCHITECTURAL_STYLE TOTAL_AREA BASE_AREA BASEMENT_AREA BASEMENT_FINISHED_AREA PARKING_AREA   LAND_VALUE LAST_SALE_PRICE LAST_SALE_DATE  MARKET_VALUE LAST_SALE_UPSF
0                NaN         NaN            NaN             NaN        NaN         NaN                       NaN       NaN        NaN             NaN          NaN                      NaN        NaN       NaN           NaN                    NaN          NaN          NaN             NaN            NaN           NaN            NaN
1  200 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1900 AC      2012.0  R - 35 - Average to Good       4.0        3.0             1.0          6.0  2STY - 2 Story Building      2,287     1,217         1,070                    730          420  $37,800.00     $195,144.00       9/24/2012  $299,684.00         $85.33
2  202 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1400 AC      2012.0  R - 35 - Average to Good       3.0        2.0             0.0          5.0  1STY - 1 Story Building      1,292     1,292         1,276                      0          420       $0.00     $166,710.00       2/15/2013  $221,658.00        $129.03
3  204 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1500 AC      2009.0  R - 35 - Average to Good       3.0        2.0             1.0          5.0  2STY - 2 Story Building      1,728       864           864                      0          441  $42,000.00     $197,000.00       11/3/2014  $245,964.00        $114.00
4  206 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1500 AC      2010.0  R - 35 - Average to Good       3.0        2.0             1.0          5.0  2STY - 2 Story Building      1,728       864           864                      0          441  $37,800.00     $182,970.00      12/30/2010  $237,692.00        $105.89

In [58]:
# Reading unseen dataset
unseen_data = file_path.replace("input-data\\st-peters\\","")
unseen_data = pd.read_csv(unseen_data + "unseen_data.csv")

# Filtering source dataset as per unseen data

subdivision = unseen_data['SUBDIVISION'].values
address = unseen_data['MAILING_ADDR'].values

df_new = df_new[df_new['SUBDIVISION'].isin(subdivision)].copy()
df_new = df_new[~df_new['MAILING_ADDR'].isin(address)].copy().reset_index(drop=True)

In [59]:
df_new = df_new[~((df_new.QUALITY_CODE == 'C - Not used') | (df_new.LAST_SALE_PRICE.isnull()))].copy().reset_index(drop=True) # Removing any non residential data
df_backup = df_new.copy()
df_new.head()

        MAILING_ADDR MAILING_ZIP    SUBDIVISION SCHOOL_DISTRICT   LOT_SIZE  YEAR_BUILT              QUALITY_CODE  BEDROOMS  BATHROOMS  HALF_BATHROOMS  TOTAL_ROOMS      ARCHITECTURAL_STYLE TOTAL_AREA BASE_AREA BASEMENT_AREA BASEMENT_FINISHED_AREA PARKING_AREA   LAND_VALUE LAST_SALE_PRICE LAST_SALE_DATE  MARKET_VALUE LAST_SALE_UPSF
0  200 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1900 AC      2012.0  R - 35 - Average to Good       4.0        3.0             1.0          6.0  2STY - 2 Story Building      2,287     1,217         1,070                    730          420  $37,800.00     $195,144.00       9/24/2012  $299,684.00         $85.33
1  202 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1400 AC      2012.0  R - 35 - Average to Good       3.0        2.0             0.0          5.0  1STY - 1 Story Building      1,292     1,292         1,276                      0          420       $0.00     $166,710.00       2/15/2013  $221,658.00        $129.03
2  204 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1500 AC      2009.0  R - 35 - Average to Good       3.0        2.0             1.0          5.0  2STY - 2 Story Building      1,728       864           864                      0          441  $42,000.00     $197,000.00       11/3/2014  $245,964.00        $114.00
3  206 BELLEMEADE DR       63376  BELLEMEADE #1    Fort Zumwalt  0.1500 AC      2010.0  R - 35 - Average to Good       3.0        2.0             1.0          5.0  2STY - 2 Story Building      1,728       864           864                      0          441  $37,800.00     $182,970.00      12/30/2010  $237,692.00        $105.89
4   110 BELLEROSA DR       63122  BELLEMEADE #1    Fort Zumwalt  0.1400 AC      2012.0  R - 35 - Average to Good       3.0        3.0             0.0          5.0  1STY - 1 Story Building      1,376     1,376         1,364                    818          400       $0.00     $166,000.00        8/1/2013  $236,065.00        $120.64

In [60]:
df_new = df_backup.copy()

# Removing any rows without sale year

df_new = df_new[df_new.LAST_SALE_DATE.notnull()].copy().reset_index(drop=True)


# Fixing the lot size
df_new['start'] = np.where(df_new.LOT_SIZE.str.find('AC') == -1, df_new.LOT_SIZE.str.split('X') , df_new.LOT_SIZE.str.replace(pat=" AC", repl=""))
df_new['start'][df_new.LOT_SIZE.str.find('AC') == -1] = df_new['start'][df_new.LOT_SIZE.str.find('AC') == -1].apply(lambda x: list(map(float, x)))
df_new['start'][df_new.LOT_SIZE.str.find('AC') == -1]  = df_new['start'][df_new.LOT_SIZE.str.find('AC') == -1].apply(lambda x: np.prod(x[0:2])/43560)
df_new['LOTS_SIZE'] = pd.to_numeric(df_new['start'])

# Fixing all numeric data types
df_new['TOTAL_AREA'] = df_new['TOTAL_AREA'].str.replace('[,$]','', regex=True).astype('float32')
df_new['BASE_AREA'] = df_new['BASE_AREA'].str.replace('[,$]','', regex=True).astype('float32')
df_new['BASEMENT_AREA'] = df_new['BASEMENT_AREA'].str.replace('[,$]','', regex=True).astype('float32')
df_new['BASEMENT_FINISHED_AREA'] = df_new['BASEMENT_FINISHED_AREA'].str.replace('[,$]','', regex=True).astype('float32')
df_new['PARKING_AREA'] = df_new['PARKING_AREA'].str.replace('[,$]','', regex=True).astype('float32')
df_new['LAND_VALUE'] = df_new['LAND_VALUE'].str.replace('[,$]','', regex=True).astype('float64')
df_new['LAST_SALE_PRICE'] = df_new['LAST_SALE_PRICE'].str.replace('[,$]','', regex=True).astype('float64')
df_new = df_new[df_new['LAST_SALE_PRICE'] != 0].copy().reset_index(drop=True)
df_new['MARKET_VALUE'] = df_new['MARKET_VALUE'].str.replace('[,$]','', regex=True).astype('float64')

# Extracting features from date values
df_new['LAST_SALE_DATE'] = pd.to_datetime(df_new['LAST_SALE_DATE'])

# Generating useful information from date values

df_new['SALE_DATE_YR'] = df_new['LAST_SALE_DATE'].dt.year
df_new['AGE_OF_HOUSE_AT_SALE'] = df_new['SALE_DATE_YR'] - df_new['YEAR_BUILT']
df_new['SALE_DATE_MNTH'] = df_new['LAST_SALE_DATE'].dt.month
df_new['SALE_DATE_DT'] = df_new['LAST_SALE_DATE'].dt.day

C:\Users\sivac\miniconda3\envs\myDefaultEnv\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\sivac\miniconda3\envs\myDefaultEnv\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [61]:
# Removed Items - 'QUALITY_CODE', 'ARCHITECTURAL_STYLE', 'SALE_DATE_MNTH', 'LOTS_SIZE', 'SALE_DATE_YR', 'BASEMENT_AREA',

df_new = df_new[[ 'BEDROOMS', 'BATHROOMS','HALF_BATHROOMS', 'TOTAL_ROOMS', 'TOTAL_AREA',
          'BASE_AREA',  'BASEMENT_FINISHED_AREA', 'PARKING_AREA','LAND_VALUE', 'LAST_SALE_PRICE','MARKET_VALUE',
           'AGE_OF_HOUSE_AT_SALE']].copy().drop_duplicates().reset_index(drop=True)

df_new = pd.get_dummies(df_new)
df_new.head()

   BEDROOMS  BATHROOMS  HALF_BATHROOMS  TOTAL_ROOMS  TOTAL_AREA  BASE_AREA  BASEMENT_FINISHED_AREA  PARKING_AREA  LAND_VALUE  LAST_SALE_PRICE  MARKET_VALUE  AGE_OF_HOUSE_AT_SALE
0       4.0        3.0             1.0          6.0      2287.0     1217.0                   730.0         420.0     37800.0         195144.0      299684.0                   0.0
1       3.0        2.0             0.0          5.0      1292.0     1292.0                     0.0         420.0         0.0         166710.0      221658.0                   1.0
2       3.0        2.0             1.0          5.0      1728.0      864.0                     0.0         441.0     42000.0         197000.0      245964.0                   5.0
3       3.0        2.0             1.0          5.0      1728.0      864.0                     0.0         441.0     37800.0         182970.0      237692.0                   0.0
4       3.0        3.0             0.0          5.0      1376.0     1376.0                   818.0         400.0         0.0         166000.0      236065.0                   1.0

# Data Transformation

In [62]:
# df_new['LAST_SALE_DATE'] = pd.to_datetime(df_new['LAST_SALE_DATE'], format="%b %d %Y %I:%M:%S:%f%p")

# # Generating useful information from date values

# df_new['SALE_DATE_YR'] = df_new['LAST_SALE_DATE'].dt.year
# df_new['AGE_OF_HOUSE_AT_SALE'] = df_new['SALE_DATE_YR'] - df_new['YRBLT']
# df_new['SALE_DATE_MNTH'] = df_new['LAST_SALE_DATE'].dt.month
# df_new['SALE_DATE_DT'] = df_new['LAST_SALE_DATE'].dt.day
# df_new.drop(['LAST_SALE_DATE', 'YRBLT', 'USPF', 'PHYS'], axis=1, inplace=True)
# df_new = pd.get_dummies(df_new)
# df_new.head()

In [63]:
print(df_new.shape)
df_new.dropna(inplace=True, axis=0)
print(df_new.shape)

(240, 12)
(239, 12)

In [64]:
from sklearn.model_selection import train_test_split

df_y = df_new['LAST_SALE_PRICE']
df_x = df_new.drop('LAST_SALE_PRICE', axis=1)

x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.25, random_state = 2)
print(f' Training dataset shape: {x_train.shape} | Testing dataset shape: {x_test.shape}')

 Training dataset shape: (179, 11) | Testing dataset shape: (60, 11)

In [65]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

model = LinearRegression()
model.fit(x_train, y_train)

# print(model.intercept_)
# print(model.coef_)
y_pred = model.predict(x_test)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(f'{df.head()} \n')

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R-squared:', metrics.r2_score(y_test, y_pred, multioutput='uniform_average'))

# https://www.analyticsvidhya.com/blog/2021/05/all-you-need-to-know-about-your-first-machine-learning-model-linear-regression/
# https://www.analyticsvidhya.com/blog/2021/07/an-introduction-to-linear-regression/
# https://www.analyticsvidhya.com/blog/2021/06/getting-started-with-machine-learning%e2%80%8a-%e2%80%8aimplementing-linear-regression-from-scratch/

       Actual      Predicted
35   229000.0  228020.989820
53   168103.0  172697.110372
24   205000.0  223410.194742
54   222500.0  194619.224017
153  257000.0  316547.107909

Mean Absolute Error: 23890.11286626058
Mean Squared Error: 1138666307.4657815
Root Mean Squared Error: 33744.12997049682
R-squared: 0.835720873408595

# Predicting unknown dataset

In [66]:
# Fixing the lot size
unseen_data['start'] = np.where(unseen_data.LOT_SIZE.str.find('AC') == -1, unseen_data.LOT_SIZE.str.split('X') , unseen_data.LOT_SIZE.str.replace(pat=" AC", repl=""))
unseen_data['start'][unseen_data.LOT_SIZE.str.find('AC') == -1] = unseen_data['start'][unseen_data.LOT_SIZE.str.find('AC') == -1].apply(lambda x: list(map(float, x)))
unseen_data['start'][unseen_data.LOT_SIZE.str.find('AC') == -1]  = unseen_data['start'][unseen_data.LOT_SIZE.str.find('AC') == -1].apply(lambda x: np.prod(x[0:2])/43560)
unseen_data['LOTS_SIZE'] = pd.to_numeric(unseen_data['start'])

# Fixing all numeric data types
unseen_data['TOTAL_AREA'] = unseen_data['TOTAL_AREA'].str.replace('[,$]','', regex=True).astype('float32')
unseen_data['BASE_AREA'] = unseen_data['BASE_AREA'].str.replace('[,$]','', regex=True).astype('float32')
unseen_data['BASEMENT_AREA'] = unseen_data['BASEMENT_AREA'].str.replace('[,$]','', regex=True).astype('float32')
#unseen_data['BASEMENT_FINISHED_AREA'] = unseen_data['BASEMENT_FINISHED_AREA'].str.replace('[,$]','', regex=True).astype('float32')
# unseen_data['PARKING_AREA'] = unseen_data['PARKING_AREA'].str.replace('[,$]','', regex=True).astype('float32')
unseen_data['LAND_VALUE'] = unseen_data['LAND_VALUE'].str.replace('[,$]','', regex=True).astype('float64')
unseen_data['LAST_SALE_PRICE'] = unseen_data['LAST_SALE_PRICE'].str.replace('[,$]','', regex=True).astype('float64')
#unseen_data = unseen_data[unseen_data['LAST_SALE_PRICE'] != 0].copy().reset_index(drop=True)
unseen_data['MARKET_VALUE'] = unseen_data['MARKET_VALUE'].str.replace('[,$]','', regex=True).astype('float64')

# Extracting features from date values
unseen_data['LAST_SALE_DATE'] = pd.to_datetime(unseen_data['LAST_SALE_DATE'])

# Generating useful information from date values

unseen_data['SALE_DATE_YR'] = dt.date.today().year
unseen_data['AGE_OF_HOUSE_AT_SALE'] = (dt.date.today().year)  - (unseen_data['YEAR_BUILT'])
unseen_data['SALE_DATE_MNTH'] = dt.date.today().month
unseen_data['SALE_DATE_DT'] = dt.date.today().day


unseen_data = unseen_data[[ 'BEDROOMS', 'BATHROOMS','HALF_BATHROOMS', 'TOTAL_ROOMS', 'TOTAL_AREA',
          'BASE_AREA',  'BASEMENT_FINISHED_AREA', 'PARKING_AREA','LAND_VALUE', 'MARKET_VALUE',
           'AGE_OF_HOUSE_AT_SALE']].copy().drop_duplicates().reset_index(drop=True)

unseen_data = pd.get_dummies(unseen_data)

C:\Users\sivac\miniconda3\envs\myDefaultEnv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\sivac\miniconda3\envs\myDefaultEnv\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [67]:
#unseen_data = unseen_data_backup.copy()
unseen_data

   BEDROOMS  BATHROOMS  HALF_BATHROOMS  TOTAL_ROOMS  TOTAL_AREA  BASE_AREA  BASEMENT_FINISHED_AREA  PARKING_AREA  LAND_VALUE  MARKET_VALUE  AGE_OF_HOUSE_AT_SALE
0         3          2               0            5      1626.0     1626.0                       0           400     41582.0      270512.0                     9
1         3          2               1            6      2343.0     2343.0                       0           483         0.0      384425.0                     8

In [68]:
unseen_data_backup = unseen_data.copy()

In [69]:
predicted_price = model.predict(unseen_data)
df = pd.DataFrame({'Address': address, 'Predicted': predicted_price})
df

             Address      Predicted
0  1118 NASHVILLE ST  261768.259923
1  1128 NASHVILLE ST  354319.140890

# Visualizations

In [ ]:
numericCols = df_new.select_dtypes(include=['float64','int64'])

# Calculate Correlation
corr = numericCols.corr()
# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})